### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by daemonenstall** [cosote/ha-async-tcp-proxy#2]
Hi,

unfortunately the installation fails on my system with the following message:
"The command '/bin/ash -o pipefail -c pip install PySocks' returned a non-zero code: 1
![grafik](https://github.com/cosote/ha-async-tcp-proxy/assets/69319145/c2cb087a-5b13-4dba-b2cd-89354c660348)

HASS OS is running as a virtual machine on a Proxmox server.
Core 2024.7.1
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240705.0

**Comment by john8329** [comment]
Same, unfortunately the component is unusable

**Comment by cosote** [comment]
PySocks was not used - don't remember why I had it in. Anyway, it's now removed and installation is working again.
